#!/usr/bin/env bash
#configure nginx server to listen for port 80 as before
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
